name: know_waste
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  cloud_functions: ^4.3.4
  firebase_storage: ^11.2.5

  # UI
  google_fonts: ^5.1.0
  cached_network_image: ^3.2.3
  flutter_markdown: ^0.6.17
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  percent_indicator: ^4.2.3
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0

  # Util
  dio: ^5.3.2
  hive: ^2.2.3
  go_router: ^10.0.0
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  image_picker: ^1.0.2
  uuid: ^3.0.7
  camera: ^0.10.5+3
  intl: ^0.18.1

  # Freezed
  freezed: ^2.4.2
  build_runner: ^2.4.6
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
